create table student(
    id bigint generated by default as identity,
    birthday date,
    first_name varchar(255),
    last_name varchar(255),
    group_id bigint,
    primary key (id)
                    );

create table student_group (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
                           );

create table subject (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
                     );

create table subject_group (
    subject_id bigint not null,
    group_id bigint not null,
    primary key (subject_id, group_id)
                           );

create table teacher (
    id bigint generated by default as identity,
    first_name varchar(255),
    last_name varchar(255),
    subject_id bigint, primary key (id)
                     );

alter table student add constraint FKqf0jwa26tqevbiu10cx0jggkf foreign key (group_id) references student_group;
alter table subject_group add constraint FKhow6t95igytwdjutoysohhr4i foreign key (group_id) references student_group;
alter table subject_group add constraint FK6xmk79mni0ym06e6wsiycs7hi foreign key (subject_id) references subject;
alter table teacher add constraint FKnmpwvbgxwxhy9ifnnsjcj1ir9 foreign key (subject_id) references subject;
